### ISSUE TITLE
UILabel occupy all 

### ISSUE THREAD

**Issue by iosephmagno** [collinjackson/flutter_native_label#2]
UIlabel shoul occupy only the space required to display text (like flutter text), and not fill in the entire space. Pic and demo code attached.

https://github.com/indjec/ui-label

![46C50D2D-CBDD-4A1F-8BEF-D3E6AA4C603D](https://user-images.githubusercontent.com/83366073/172040772-62f5618d-39df-46e2-b856-667a6c2e3dc2.png)

**Comment by iosephmagno** [comment]
It seems it might be a little issue that breaks UIlabel intrinsic width in the native code. Width is defined but noticed an InvalidateIntrinsicContextSize somewhere and maybe it is it.
https://github.com/collinjackson/flutter_native_label/blob/main/ios/Classes/NativeLabel.m


Also, Size is broken in the constructor
<img width="765" alt="B6FA3EF8-AE23-4878-B66D-DE552F90B29D" src="https://user-images.githubusercontent.com/83366073/174018649-2759dede-3506-4f09-a772-c5397a6cfccf.png">

**Comment by collinjackson** [comment]
Using the branch from #4, here's what it looks like

<img width="561" alt="Screen Shot 2022-06-16 at 11 07 59 AM" src="https://user-images.githubusercontent.com/394889/174137351-12246fdd-e4b1-448d-8d1d-85ebc0bbbcac.png">
